### ISSUE TITLE
Missing image name from docker command in documentation

### ISSUE THREAD

**Issue by nicktgr15** [sequenceiq/docker-ambari-shell#1]
Hello,

I think you need an image name for the docker command under **Option-A: Ambari Server on docker**. 

This is what I get.

```
$ docker run --link amb0:ambariserver -e EXPECTED_HOST_COUNT=1 -it --rm --entrypoint /bin/sh shell -c /tmp/wait-for-host-number.sh
Unable to find image 'shell:latest' locally
Pulling repository shell
FATA[0001] Error: image library/shell:latest not found
```

Regards,
Nik

**Comment by nicktgr15** [comment]
Worked after changing it into:

```
docker run --link ambari-singlenode:ambariserver -e EXPECTED_HOST_COUNT=1 -it --rm --entrypoint /bin/sh sequenceiq/ambari-shell -c /tmp/wait-for-host-number.sh
```

**Comment by matyix** [comment]
Thanks a lot for your input, just updating it now. Recently we use these https://github.com/sequenceiq/docker-ambari/blob/1.7.0/ambari-functions - simplified version of typing in those long commands.

**Comment by gumorxmt** [comment]
I install docker again as https://docs.docker.com/engine/installation/ubuntulinux/. And REMEMBER

**Comment by gumorxmt** [comment]
I install docker again as https://docs.docker.com/engine/installation/ubuntulinux/. And REMEMBER to reboot. Then problem solved.
